version: 2
updates:
  # 1. Security updates only (daily)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    security-updates-only: true
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"
    commit-message:
      prefix: "[Security] "

  # 2. Regular version bumps (monthly)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "[Chore] "
