spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

auth:
  jwt:
    access_token_expiration: 900000 # 15 minutes
    refresh_token_expiration: 86400000 # 24 hours
    secret: ${JWT_SECRET_KEY}

smtp:
  host: "smtp.gmail.com"
  port: 587
  email: ${SMTP_ACCOUNT_EMAIL}
  password: ${SMTP_ACCOUNT_PASSWORD}

openai:
  api:
    organization_id: ${OPENAI_API_ORGANIZATION_ID}
    project_id: ${OPENAI_API_PROJECT_ID}
    key: ${OPENAI_API_KEY}
  model:
    name: "gpt-4o-mini"
