spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    # Disable prepared statements for SupaBase
    hikari:
      cache-prep-stmts: false
      prep-stmt-cache-size: 0
      prep-stmt-cache-sql-limit: 0
      use-server-prep-stmts: false
      use-local-session-state: true
      use-local-transaction-state: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

app:
  base-url: "http://localhost:8080"

auth:
  jwt:
    access-token-expiration: 900000 # 15 minutes
    refresh-token-expiration: 86400000 # 24 hours
    secret: ${JWT_SECRET_KEY}
  verification:
    email-token-expiration: 86400000 # 24 hours
    password-token-expiration: 3600000 # 1 hour

smtp:
  host: "smtp.gmail.com"
  port: 587
  email: ${SMTP_ACCOUNT_EMAIL}
  password: ${SMTP_ACCOUNT_PASSWORD}

openai:
  api:
    organization-id: ${OPENAI_API_ORGANIZATION_ID}
    project-id: ${OPENAI_API_PROJECT_ID}
    key: ${OPENAI_API_KEY}
  model:
    name: "gpt-4o-mini"

cloudinary:
  api-url: ${CLOUDINARY_URL}
