spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
openai:
  api:
    organization_id: ${OPENAI_API_ORGANIZATION_ID}
    project_id: ${OPENAI_API_PROJECT_ID}
    key: ${OPENAI_API_KEY}
  model:
    name: "gpt-4o-mini"
