name: Java CI with Maven

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: ${{ vars.SPRING_PROFILES_ACTIVE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Copy Artifact
        run: mkdir staging && cp -p target/*.jar staging
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codespark-backend
          path: staging
          retention-days: 1

      - name: Update dependency graph
        if: github.event_name == 'push'
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          ignore-maven-wrapper: true
